### ISSUE TITLE
感谢大佬开源

### ISSUE THREAD

**Issue by sevenold** [YangHan-Morningstar/chatterbot#1]
- 不知道实现效果，希望大佬更新下效果
- 想要复现项目，希望大佬提供数据集和参数文件

谢谢！！！

**Comment by YangHan-Morningstar** [comment]
你可以在我的百度网盘链接中获取数据集和效果图
链接: https://pan.baidu.com/s/1G5xk58biY12gmQFrrBghkg  密码: hmnm

**Comment by sevenold** [comment]
thanks

**Comment by yuanupcom** [comment]
> thanks

您好，作者提供的数据集即参数，网盘已经过期，请问您还存有数据集和参数文件吗？
